### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by fluktuid** [fluktuid/lan-tournament-manager#4]
Einen QR-Code, mit Nutzername und auth token, damit der Nutzer sich leicht über denselben Account anmelden kann, Zusätzlich können Links erstellt werden

- [ ] auth QR erstellen
- [x] links erstellen

**Comment by fluktuid** [comment]
[zxing](https://github.com/zxing/zxing) ist meiner Erfahrung nach die beste Lib dafür

**Comment by fluktuid** [comment]
vgl. https://www.callicoder.com/generate-qr-code-in-java-using-zxing/

**Comment by fluktuid** [comment]
@MalteSchwitters Muss der QRCodeGenerator noch etwas Anderes als Links und die AuthToken erstellen können?

**Comment by MalteSchwitters** [comment]
Nein, eigentlich muss er nur den Link erzeugen. Das Token sollte dem Generator mitgegeben werden.

**Comment by fluktuid** [comment]
Kay, dann ist der Generator soweit fertig.
Wer Bock hat kann ja noch nen Test schreiben.
